version: '3.8'

services:
  react-app:
    image: "${DOCKER_IMAGE:-vijayganesh5/devops-build-dev:latest}"  # Default to DEV image
    container_name: react-app
    ports:
      - "80:80"
    restart: unless-stopped

